  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Awards"
  weight = 500
  identifier = "awards"
  url = "/awards/"

  [[main]]
  name = "Certifications"
  weight = 600
  identifier = "certifications"
  url = "/certifications/"
